language: ko-KR

reviews:
  profile: chill  # chill, balanced, strict 중 선택 가능 (보통 chill이 자연스럽고 부담 없음)
  high_level_summary: true
  changed_files_summary: true

  path_instructions:
    - path: "**/*"
      instructions: |
        리뷰 목표:
        - 복잡하거나 중복되는 로직을 간결하게 바꿀 수 있는 방안을 제안해줘
        - 코드 흐름이 애매한 부분은 어떤 구조로 바꾸면 좋을지 설명해줘
        - 하나의 함수/클래스가 여러 책임을 질 경우 단일 책임 원칙 관점에서 나눠달라고 제안해줘
        - 클린 아키텍처 위반(예: Presentation이 Data를 직접 참조)을 지적해줘
        - async/await이나 Rx 코드에서 비효율적이거나 중복된 흐름을 알려줘
        - 메모리 누수 가능성 있는 코드(예: [weak self] 누락 등)를 지적해줘
        - “왜” 고쳐야 하는지 이유까지 간단히 설명해줘
        - 커밋 메시지가 기능에 맞게 작성됐는지도 가볍게 피드백해줘

        피해야 할 것:
        - 스타일이나 줄 길이, 띄어쓰기 등 사소한 포맷 코멘트는 하지 마
        - 변수명 선호나 네이밍 감성은 지적하지 마
        - 주석 많고 적음에 대한 피드백은 하지 마
        - 테스트 코드 누락에 대한 지적은 하지 마
